/**
 * Comprehensive authentic movie library containing 100+ top films across all genres,
 * decades (1970 - 2026), and rating categories.
 * Used when TMDB_API_KEY is not configured in .env, or as offline resilience.
 */

export const DEMO_MOVIES = [
  // --- HORROR & MYSTERY & THRILLER ---
  {
    id: 11324,
    title: "Shutter Island",
    originalTitle: "Shutter Island",
    releaseDate: "2010-02-18",
    year: 2010,
    poster: "https://image.tmdb.org/t/p/w500/4GDy0PHYX3VRXUtwK5ysagvk29z.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/c9XLA2qGf48kG1nQe96U5Z1Vn9A.jpg",
    overview: "World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from Boston's Shutter Island Ashecliffe Hospital.",
    genres: ["Mystery", "Thriller", "Drama"],
    genreIds: [9648, 53, 18],
    popularity: 92.4,
    tmdbRating: 8.2,
    tmdbVotes: 23800,
    formattedTmdbVotes: "23.8K",
    imdbId: "tt1130884",
    imdbRating: 8.2,
    imdbVotes: 1450000,
    formattedImdbVotes: "1.4M",
    qualityScore: 8.24,
    runtime: 138,
    formattedRuntime: "2h 18m",
    director: "Martin Scorsese",
    trailerKey: "v8HKTr8XWBU",
    rottenTomatoes: "69%",
    metascore: "63",
    rated: "R"
  },
  {
    id: 138843,
    title: "The Conjuring",
    originalTitle: "The Conjuring",
    releaseDate: "2013-07-18",
    year: 2013,
    poster: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5E1T1rJjG4j3G7hG3lQk2H1z8oP.jpg",
    overview: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    genres: ["Horror", "Mystery", "Thriller"],
    genreIds: [27, 9648, 53],
    popularity: 78.5,
    tmdbRating: 7.5,
    tmdbVotes: 11400,
    formattedTmdbVotes: "11.4K",
    imdbId: "tt1457767",
    imdbRating: 7.5,
    imdbVotes: 560000,
    formattedImdbVotes: "560K",
    qualityScore: 7.52,
    runtime: 112,
    formattedRuntime: "1h 52m",
    director: "James Wan",
    trailerKey: "k10ETZ41q5o",
    rottenTomatoes: "86%",
    metascore: "68",
    rated: "R"
  },
  {
    id: 493922,
    title: "Hereditary",
    originalTitle: "Hereditary",
    releaseDate: "2018-06-07",
    year: 2018,
    poster: "https://image.tmdb.org/t/p/w500/lHV8HHlhwv9RpmKCb7yy8wf4wm7.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yG28j5U8mN1lQ9X7vF8r4w6hL4t.jpg",
    overview: "When Ellen, the matriarch of the Graham family, passes away, her daughter's family begins to unravel cryptic and terrifying secrets.",
    genres: ["Horror", "Mystery", "Drama"],
    genreIds: [27, 9648, 18],
    popularity: 64.2,
    tmdbRating: 7.3,
    tmdbVotes: 7500,
    formattedTmdbVotes: "7.5K",
    imdbId: "tt7784604",
    imdbRating: 7.3,
    imdbVotes: 410000,
    formattedImdbVotes: "410K",
    qualityScore: 7.33,
    runtime: 127,
    formattedRuntime: "2h 7m",
    director: "Ari Aster",
    trailerKey: "V6wWKNij_1M",
    rottenTomatoes: "90%",
    metascore: "87",
    rated: "R"
  },
  {
    id: 419430,
    title: "Get Out",
    originalTitle: "Get Out",
    releaseDate: "2017-02-24",
    year: 2017,
    poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/m5zkv6n1g8l9x7p6v4w2y1z5mNy.jpg",
    overview: "Chris and his girlfriend Rose visit her parents for the weekend, where a series of disturbing discoveries lead him to a terrifying truth.",
    genres: ["Mystery", "Thriller", "Horror"],
    genreIds: [9648, 53, 27],
    popularity: 58.1,
    tmdbRating: 7.6,
    tmdbVotes: 17200,
    formattedTmdbVotes: "17.2K",
    imdbId: "tt5052448",
    imdbRating: 7.8,
    imdbVotes: 710000,
    formattedImdbVotes: "710K",
    qualityScore: 7.81,
    runtime: 104,
    formattedRuntime: "1h 44m",
    director: "Jordan Peele",
    trailerKey: "DzfpyUB60YY",
    rottenTomatoes: "98%",
    metascore: "85",
    rated: "R"
  },
  {
    id: 807,
    title: "Se7en",
    originalTitle: "Se7en",
    releaseDate: "1995-09-22",
    year: 1995,
    poster: "https://image.tmdb.org/t/p/w500/6yoghtyTBoPvxwvmpujflPgnAcF.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bGksau9GIlUBVIqFJVR69cOW5Hp.jpg",
    overview: "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the seven deadly sins.",
    genres: ["Crime", "Mystery", "Thriller"],
    genreIds: [80, 9648, 53],
    popularity: 88.3,
    tmdbRating: 8.4,
    tmdbVotes: 21100,
    formattedTmdbVotes: "21.1K",
    imdbId: "tt0114369",
    imdbRating: 8.6,
    imdbVotes: 1800000,
    formattedImdbVotes: "1.8M",
    qualityScore: 8.62,
    runtime: 127,
    formattedRuntime: "2h 7m",
    director: "David Fincher",
    trailerKey: "znmZoVkCjpI",
    rottenTomatoes: "83%",
    metascore: "65",
    rated: "R"
  },
  {
    id: 745,
    title: "The Sixth Sense",
    originalTitle: "The Sixth Sense",
    releaseDate: "1999-08-06",
    year: 1999,
    poster: "https://image.tmdb.org/t/p/w500/4AfSDjjCy6T5LA1BCz6bg9wm2NZ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/l69XQ3w8v2y1z5mNy6hL4tY9X7.jpg",
    overview: "A child psychologist tries to help a young boy who communicates with spirits who don't know they're dead.",
    genres: ["Mystery", "Thriller", "Drama"],
    genreIds: [9648, 53, 18],
    popularity: 52.4,
    tmdbRating: 8.0,
    tmdbVotes: 11500,
    formattedTmdbVotes: "11.5K",
    imdbId: "tt0167404",
    imdbRating: 8.2,
    imdbVotes: 1100000,
    formattedImdbVotes: "1.1M",
    qualityScore: 8.21,
    runtime: 107,
    formattedRuntime: "1h 47m",
    director: "M. Night Shyamalan",
    trailerKey: "VG9AGf66tXM",
    rottenTomatoes: "86%",
    metascore: "64",
    rated: "PG-13"
  },
  {
    id: 1933,
    title: "The Others",
    originalTitle: "The Others",
    releaseDate: "2001-08-02",
    year: 2001,
    poster: "https://image.tmdb.org/t/p/w500/p11vQgB5Wb2XzXqE52x6Z1N6P5m.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7k8l9x7p6v4w2y1z5mNy6hL4tY9.jpg",
    overview: "A devout woman with two photosensitive children is convinced that the family's home is haunted after several bizarre events occur.",
    genres: ["Horror", "Mystery", "Thriller"],
    genreIds: [27, 9648, 53],
    popularity: 38.6,
    tmdbRating: 7.6,
    tmdbVotes: 6400,
    formattedTmdbVotes: "6.4K",
    imdbId: "tt0230600",
    imdbRating: 7.6,
    imdbVotes: 400000,
    formattedImdbVotes: "400K",
    qualityScore: 7.62,
    runtime: 104,
    formattedRuntime: "1h 44m",
    director: "Alejandro Amenábar",
    trailerKey: "0bMEmt396Tk",
    rottenTomatoes: "84%",
    metascore: "74",
    rated: "PG-13"
  },
  {
    id: 694,
    title: "The Shining",
    originalTitle: "The Shining",
    releaseDate: "1980-05-23",
    year: 1980,
    poster: "https://image.tmdb.org/t/p/w500/xazWoLealQwEgqZ89MLZklLZD3k.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mmd1HNu2R6Q51qL0Uq8WwJ3UfM5.jpg",
    overview: "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter.",
    genres: ["Horror", "Thriller"],
    genreIds: [27, 53],
    popularity: 76.2,
    tmdbRating: 8.2,
    tmdbVotes: 17300,
    formattedTmdbVotes: "17.3K",
    imdbId: "tt0081505",
    imdbRating: 8.4,
    imdbVotes: 1150000,
    formattedImdbVotes: "1.1M",
    qualityScore: 8.41,
    runtime: 146,
    formattedRuntime: "2h 26m",
    director: "Stanley Kubrick",
    trailerKey: "S014S9upxNw",
    rottenTomatoes: "83%",
    metascore: "66",
    rated: "R"
  },
  {
    id: 447332,
    title: "A Quiet Place",
    originalTitle: "A Quiet Place",
    releaseDate: "2018-04-03",
    year: 2018,
    poster: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/roYyPiQDytnk0yuHI6b92vr5v53.jpg",
    overview: "A family must navigate their lives in silence to avoid mysterious creatures that hunt by sound.",
    genres: ["Horror", "Drama", "Science Fiction"],
    genreIds: [27, 18, 878],
    popularity: 62.4,
    tmdbRating: 7.4,
    tmdbVotes: 14100,
    formattedTmdbVotes: "14.1K",
    imdbId: "tt6644200",
    imdbRating: 7.5,
    imdbVotes: 610000,
    formattedImdbVotes: "610K",
    qualityScore: 7.52,
    runtime: 90,
    formattedRuntime: "1h 30m",
    director: "John Krasinski",
    trailerKey: "WR7cc5t7tv8",
    rottenTomatoes: "96%",
    metascore: "82",
    rated: "PG-13"
  },
  {
    id: 530385,
    title: "Midsommar",
    originalTitle: "Midsommar",
    releaseDate: "2019-07-03",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/7LEI8ulBsdu7QnzWAr2neacyvBP.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/g67eI59sK9VzL4v6Xv5m1z5mNy6.jpg",
    overview: "A couple travels to Northern Europe to visit a rural hometown's fabled Swedish mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition.",
    genres: ["Horror", "Drama", "Mystery"],
    genreIds: [27, 18, 9648],
    popularity: 58.7,
    tmdbRating: 7.1,
    tmdbVotes: 6900,
    formattedTmdbVotes: "6.9K",
    imdbId: "tt8772262",
    imdbRating: 7.1,
    imdbVotes: 420000,
    formattedImdbVotes: "420K",
    qualityScore: 7.12,
    runtime: 148,
    formattedRuntime: "2h 28m",
    director: "Ari Aster",
    trailerKey: "1Vnghdsjmd0",
    rottenTomatoes: "83%",
    metascore: "72",
    rated: "R"
  },
  {
    id: 1091,
    title: "The Thing",
    originalTitle: "The Thing",
    releaseDate: "1982-06-25",
    year: 1982,
    poster: "https://image.tmdb.org/t/p/w500/tzGY49jiZL2W6w4XnN4Bqq665b1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/t5A0g1q8l9x7p6v4w2y1z5mNy6h.jpg",
    overview: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
    genres: ["Horror", "Mystery", "Science Fiction"],
    genreIds: [27, 9648, 878],
    popularity: 68.3,
    tmdbRating: 8.0,
    tmdbVotes: 6800,
    formattedTmdbVotes: "6.8K",
    imdbId: "tt0084787",
    imdbRating: 8.2,
    imdbVotes: 470000,
    formattedImdbVotes: "470K",
    qualityScore: 8.21,
    runtime: 109,
    formattedRuntime: "1h 49m",
    director: "John Carpenter",
    trailerKey: "5ftmr17M-ZY",
    rottenTomatoes: "85%",
    metascore: "57",
    rated: "R"
  },
  {
    id: 348,
    title: "Alien",
    originalTitle: "Alien",
    releaseDate: "1979-05-25",
    year: 1979,
    poster: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/AmR3JG1DYG5ed7vmv532WfUdUt.jpg",
    overview: "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew investigates the source of the signal, they uncover an alien life form.",
    genres: ["Horror", "Science Fiction"],
    genreIds: [27, 878],
    popularity: 81.5,
    tmdbRating: 8.1,
    tmdbVotes: 14700,
    formattedTmdbVotes: "14.7K",
    imdbId: "tt0078748",
    imdbRating: 8.5,
    imdbVotes: 980000,
    formattedImdbVotes: "980K",
    qualityScore: 8.51,
    runtime: 117,
    formattedRuntime: "1h 57m",
    director: "Ridley Scott",
    trailerKey: "LjLamj-b0I8",
    rottenTomatoes: "93%",
    metascore: "89",
    rated: "R"
  },
  {
    id: 546554,
    title: "Knives Out",
    originalTitle: "Knives Out",
    releaseDate: "2019-11-27",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x8WwJ3UfM5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/Ab8mkHmkYADjU7wio7ia94IDqlj.jpg",
    overview: "When renowned crime novelist Harlan Thrombey is found dead at his estate, inquisitive Detective Benoit Blanc is mysteriously enlisted to investigate.",
    genres: ["Comedy", "Crime", "Mystery"],
    genreIds: [35, 80, 9648],
    popularity: 72.1,
    tmdbRating: 7.9,
    tmdbVotes: 12100,
    formattedTmdbVotes: "12.1K",
    imdbId: "tt8946378",
    imdbRating: 7.9,
    imdbVotes: 800000,
    formattedImdbVotes: "800K",
    qualityScore: 7.92,
    runtime: 130,
    formattedRuntime: "2h 10m",
    director: "Rian Johnson",
    trailerKey: "qGqiHJTsRfs",
    rottenTomatoes: "97%",
    metascore: "82",
    rated: "PG-13"
  },
  {
    id: 146233,
    title: "Prisoners",
    originalTitle: "Prisoners",
    releaseDate: "2013-09-18",
    year: 2013,
    poster: "https://image.tmdb.org/t/p/w500/tuZhZ6biFMr5n9X7m6L4h1z5vNz.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/c8L4tY9X7m6L4h1z5vNz8j1lQ1.jpg",
    overview: "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.",
    genres: ["Drama", "Mystery", "Thriller"],
    genreIds: [18, 9648, 53],
    popularity: 68.4,
    tmdbRating: 8.1,
    tmdbVotes: 12200,
    formattedTmdbVotes: "12.2K",
    imdbId: "tt1392214",
    imdbRating: 8.2,
    imdbVotes: 840000,
    formattedImdbVotes: "840K",
    qualityScore: 8.21,
    runtime: 153,
    formattedRuntime: "2h 33m",
    director: "Denis Villeneuve",
    trailerKey: "bpXfcT61_h0",
    rottenTomatoes: "81%",
    metascore: "70",
    rated: "R"
  },
  {
    id: 77,
    title: "Memento",
    originalTitle: "Memento",
    releaseDate: "2000-10-11",
    year: 2000,
    poster: "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9z5n9w7.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bdN3GgDkK0X3w5mNy6hL4tY9X7.jpg",
    overview: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss.",
    genres: ["Mystery", "Thriller"],
    genreIds: [9648, 53],
    popularity: 63.8,
    tmdbRating: 8.2,
    tmdbVotes: 14900,
    formattedTmdbVotes: "14.9K",
    imdbId: "tt0209144",
    imdbRating: 8.4,
    imdbVotes: 1300000,
    formattedImdbVotes: "1.3M",
    qualityScore: 8.41,
    runtime: 113,
    formattedRuntime: "1h 53m",
    director: "Christopher Nolan",
    trailerKey: "0vS0E9bBS74",
    rottenTomatoes: "93%",
    metascore: "80",
    rated: "R"
  },
  {
    id: 210577,
    title: "Gone Girl",
    originalTitle: "Gone Girl",
    releaseDate: "2014-10-01",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/qymaJhucquUwjpPV39W5fVv1nNy.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/m9X7vF8r4w6hL4tY9X7m6L4h1z.jpg",
    overview: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    genres: ["Mystery", "Thriller", "Drama"],
    genreIds: [9648, 53, 18],
    popularity: 74.3,
    tmdbRating: 7.9,
    tmdbVotes: 18400,
    formattedTmdbVotes: "18.4K",
    imdbId: "tt2267998",
    imdbRating: 8.1,
    imdbVotes: 1100000,
    formattedImdbVotes: "1.1M",
    qualityScore: 8.12,
    runtime: 149,
    formattedRuntime: "2h 29m",
    director: "David Fincher",
    trailerKey: "2-_-1nJf8Vg",
    rottenTomatoes: "88%",
    metascore: "79",
    rated: "R"
  },
  {
    id: 1124,
    title: "The Prestige",
    originalTitle: "The Prestige",
    releaseDate: "2006-10-19",
    year: 2006,
    poster: "https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpb9dt86Q51qL0U.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/y2A5b1q8l9x7p6v4w2y1z5mNy6h.jpg",
    overview: "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.",
    genres: ["Drama", "Mystery", "Science Fiction"],
    genreIds: [18, 9648, 878],
    popularity: 84.1,
    tmdbRating: 8.2,
    tmdbVotes: 16100,
    formattedTmdbVotes: "16.1K",
    imdbId: "tt0482571",
    imdbRating: 8.5,
    imdbVotes: 1500000,
    formattedImdbVotes: "1.5M",
    qualityScore: 8.51,
    runtime: 130,
    formattedRuntime: "2h 10m",
    director: "Christopher Nolan",
    trailerKey: "o4gHCmTQDVI",
    rottenTomatoes: "77%",
    metascore: "66",
    rated: "PG-13"
  },

  // --- SCIENCE FICTION & ADVENTURE ---
  {
    id: 157336,
    title: "Interstellar",
    originalTitle: "Interstellar",
    releaseDate: "2014-11-05",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel.",
    genres: ["Science Fiction", "Adventure", "Drama"],
    genreIds: [878, 12, 18],
    popularity: 145.8,
    tmdbRating: 8.4,
    tmdbVotes: 35600,
    formattedTmdbVotes: "35.6K",
    imdbId: "tt0816692",
    imdbRating: 8.7,
    imdbVotes: 2100000,
    formattedImdbVotes: "2.1M",
    qualityScore: 8.71,
    runtime: 169,
    formattedRuntime: "2h 49m",
    director: "Christopher Nolan",
    trailerKey: "zSWdZVtXT7E",
    rottenTomatoes: "73%",
    metascore: "74",
    rated: "PG-13"
  },
  {
    id: 27205,
    title: "Inception",
    originalTitle: "Inception",
    releaseDate: "2010-07-15",
    year: 2010,
    poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life.",
    genres: ["Action", "Science Fiction", "Adventure"],
    genreIds: [28, 878, 12],
    popularity: 110.2,
    tmdbRating: 8.4,
    tmdbVotes: 36200,
    formattedTmdbVotes: "36.2K",
    imdbId: "tt1375666",
    imdbRating: 8.8,
    imdbVotes: 2600000,
    formattedImdbVotes: "2.6M",
    qualityScore: 8.82,
    runtime: 148,
    formattedRuntime: "2h 28m",
    director: "Christopher Nolan",
    trailerKey: "YoHD9XEInc0",
    rottenTomatoes: "87%",
    metascore: "74",
    rated: "PG-13"
  },
  {
    id: 603,
    title: "The Matrix",
    originalTitle: "The Matrix",
    releaseDate: "1999-03-30",
    year: 1999,
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7u3fh9Am1Q7I0x3w5mNy6hL4tY9.jpg",
    overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    genres: ["Action", "Science Fiction"],
    genreIds: [28, 878],
    popularity: 120.5,
    tmdbRating: 8.2,
    tmdbVotes: 25400,
    formattedTmdbVotes: "25.4K",
    imdbId: "tt0133093",
    imdbRating: 8.7,
    imdbVotes: 2100000,
    formattedImdbVotes: "2.1M",
    qualityScore: 8.71,
    runtime: 136,
    formattedRuntime: "2h 16m",
    director: "Lilly Wachowski, Lana Wachowski",
    trailerKey: "vKQi3bBA1y8",
    rottenTomatoes: "83%",
    metascore: "73",
    rated: "R"
  },
  {
    id: 329865,
    title: "Arrival",
    originalTitle: "Arrival",
    releaseDate: "2016-11-10",
    year: 2016,
    poster: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yIZ1xendyqKvY37DCWuvi075W97.jpg",
    overview: "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
    genres: ["Science Fiction", "Mystery", "Drama"],
    genreIds: [878, 9648, 18],
    popularity: 75.9,
    tmdbRating: 7.6,
    tmdbVotes: 17800,
    formattedTmdbVotes: "17.8K",
    imdbId: "tt2543164",
    imdbRating: 7.9,
    imdbVotes: 760000,
    formattedImdbVotes: "760K",
    qualityScore: 7.91,
    runtime: 116,
    formattedRuntime: "1h 56m",
    director: "Denis Villeneuve",
    trailerKey: "tFMo3UJ4B4g",
    rottenTomatoes: "94%",
    metascore: "81",
    rated: "PG-13"
  },
  {
    id: 335984,
    title: "Blade Runner 2049",
    originalTitle: "Blade Runner 2049",
    releaseDate: "2017-10-04",
    year: 2017,
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ilRyAZwN105q9wU8A7tF8r4w6h.jpg",
    overview: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    genres: ["Science Fiction", "Mystery", "Action"],
    genreIds: [878, 9648, 28],
    popularity: 91.2,
    tmdbRating: 7.6,
    tmdbVotes: 13900,
    formattedTmdbVotes: "13.9K",
    imdbId: "tt1856101",
    imdbRating: 8.0,
    imdbVotes: 680000,
    formattedImdbVotes: "680K",
    qualityScore: 8.02,
    runtime: 164,
    formattedRuntime: "2h 44m",
    director: "Denis Villeneuve",
    trailerKey: "gCcx85zbxz4",
    rottenTomatoes: "88%",
    metascore: "81",
    rated: "R"
  },
  {
    id: 438631,
    title: "Dune",
    originalTitle: "Dune",
    releaseDate: "2021-09-15",
    year: 2021,
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94Xv5m1z5m.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    overview: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
    genres: ["Science Fiction", "Adventure"],
    genreIds: [878, 12],
    popularity: 135.2,
    tmdbRating: 7.8,
    tmdbVotes: 11800,
    formattedTmdbVotes: "11.8K",
    imdbId: "tt1160419",
    imdbRating: 8.0,
    imdbVotes: 850000,
    formattedImdbVotes: "850K",
    qualityScore: 8.02,
    runtime: 155,
    formattedRuntime: "2h 35m",
    director: "Denis Villeneuve",
    trailerKey: "n9xhJrPXop4",
    rottenTomatoes: "83%",
    metascore: "74",
    rated: "PG-13"
  },
  {
    id: 693134,
    title: "Dune: Part Two",
    originalTitle: "Dune: Part Two",
    releaseDate: "2024-02-27",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9x8WwJ3UfM5Ny.jpg",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    genres: ["Science Fiction", "Adventure"],
    genreIds: [878, 12],
    popularity: 180.4,
    tmdbRating: 8.2,
    tmdbVotes: 5900,
    formattedTmdbVotes: "5.9K",
    imdbId: "tt15239678",
    imdbRating: 8.5,
    imdbVotes: 540000,
    formattedImdbVotes: "540K",
    qualityScore: 8.51,
    runtime: 166,
    formattedRuntime: "2h 46m",
    director: "Denis Villeneuve",
    trailerKey: "Way9Dexny3w",
    rottenTomatoes: "92%",
    metascore: "79",
    rated: "PG-13"
  },
  {
    id: 280,
    title: "Terminator 2: Judgment Day",
    originalTitle: "Terminator 2: Judgment Day",
    releaseDate: "1991-07-03",
    year: 1991,
    poster: "https://image.tmdb.org/t/p/w500/5M0j0B18abtqP9x8WwJ3UfM5Ny6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/x2n7vF8r4w6hL4tY9X7m6L4h1z5.jpg",
    overview: "Nearly ten years have passed since Sarah Connor was targeted for termination. Now her son John, the future leader of the resistance, is targeted by a more deadly Terminator.",
    genres: ["Action", "Science Fiction", "Thriller"],
    genreIds: [28, 878, 53],
    popularity: 85.2,
    tmdbRating: 8.1,
    tmdbVotes: 12600,
    formattedTmdbVotes: "12.6K",
    imdbId: "tt0103064",
    imdbRating: 8.6,
    imdbVotes: 1200000,
    formattedImdbVotes: "1.2M",
    qualityScore: 8.61,
    runtime: 137,
    formattedRuntime: "2h 17m",
    director: "James Cameron",
    trailerKey: "lwSysg9o7wE",
    rottenTomatoes: "91%",
    metascore: "75",
    rated: "R"
  },
  {
    id: 329,
    title: "Jurassic Park",
    originalTitle: "Jurassic Park",
    releaseDate: "1993-06-11",
    year: 1993,
    poster: "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4Vo0AW3a97cu.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bKxiL9CuAn2Zw16cxLOi2JHZeRH.jpg",
    overview: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
    genres: ["Adventure", "Science Fiction"],
    genreIds: [12, 878],
    popularity: 95.4,
    tmdbRating: 8.0,
    tmdbVotes: 16100,
    formattedTmdbVotes: "16.1K",
    imdbId: "tt0107290",
    imdbRating: 8.2,
    imdbVotes: 1100000,
    formattedImdbVotes: "1.1M",
    qualityScore: 8.21,
    runtime: 127,
    formattedRuntime: "2h 7m",
    director: "Steven Spielberg",
    trailerKey: "lc0UehYemQA",
    rottenTomatoes: "92%",
    metascore: "68",
    rated: "PG-13"
  },

  // --- ACTION & COMEDY & DRAMA ---
  {
    id: 155,
    title: "The Dark Knight",
    originalTitle: "The Dark Knight",
    releaseDate: "2008-07-16",
    year: 2008,
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    genres: ["Drama", "Action", "Crime", "Thriller"],
    genreIds: [18, 28, 80, 53],
    popularity: 130.4,
    tmdbRating: 8.5,
    tmdbVotes: 33400,
    formattedTmdbVotes: "33.4K",
    imdbId: "tt0468569",
    imdbRating: 9.0,
    imdbVotes: 2950000,
    formattedImdbVotes: "2.9M",
    qualityScore: 9.04,
    runtime: 152,
    formattedRuntime: "2h 32m",
    director: "Christopher Nolan",
    trailerKey: "EXeTwQWrcwY",
    rottenTomatoes: "94%",
    metascore: "84",
    rated: "PG-13"
  },
  {
    id: 76341,
    title: "Mad Max: Fury Road",
    originalTitle: "Mad Max: Fury Road",
    releaseDate: "2015-05-13",
    year: 2015,
    poster: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nlCHUWjY9X7m6L4h1z5vNz8j1lQ.jpg",
    overview: "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and almost everyone is crazed fighting for the necessities of life.",
    genres: ["Action", "Adventure", "Science Fiction"],
    genreIds: [28, 12, 878],
    popularity: 88.6,
    tmdbRating: 7.6,
    tmdbVotes: 22100,
    formattedTmdbVotes: "22.1K",
    imdbId: "tt1392190",
    imdbRating: 8.1,
    imdbVotes: 1100000,
    formattedImdbVotes: "1.1M",
    qualityScore: 8.12,
    runtime: 120,
    formattedRuntime: "2h 0m",
    director: "George Miller",
    trailerKey: "hEJnMQG9ev8",
    rottenTomatoes: "97%",
    metascore: "90",
    rated: "R"
  },
  {
    id: 98,
    title: "Gladiator",
    originalTitle: "Gladiator",
    releaseDate: "2000-05-04",
    year: 2000,
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    overview: "In the year 180, the death of emperor Marcus Aurelius throws the Roman Empire into turmoil. Maximus Decimus Meridius, a victorious general, is betrayed by the ambitious Commodus.",
    genres: ["Action", "Drama", "Adventure"],
    genreIds: [28, 18, 12],
    popularity: 94.2,
    tmdbRating: 8.2,
    tmdbVotes: 18200,
    formattedTmdbVotes: "18.2K",
    imdbId: "tt0172495",
    imdbRating: 8.5,
    imdbVotes: 1650000,
    formattedImdbVotes: "1.6M",
    qualityScore: 8.51,
    runtime: 155,
    formattedRuntime: "2h 35m",
    director: "Ridley Scott",
    trailerKey: "owK1qxDselE",
    rottenTomatoes: "80%",
    metascore: "67",
    rated: "R"
  },
  {
    id: 496243,
    title: "Parasite",
    originalTitle: "기생충",
    releaseDate: "2019-05-30",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    genres: ["Comedy", "Thriller", "Drama"],
    genreIds: [35, 53, 18],
    popularity: 98.4,
    tmdbRating: 8.5,
    tmdbVotes: 18100,
    formattedTmdbVotes: "18.1K",
    imdbId: "tt6751668",
    imdbRating: 8.5,
    imdbVotes: 980000,
    formattedImdbVotes: "980K",
    qualityScore: 8.52,
    runtime: 132,
    formattedRuntime: "2h 12m",
    director: "Bong Joon-ho",
    trailerKey: "5xH0Rqa1hnE",
    rottenTomatoes: "99%",
    metascore: "96",
    rated: "R"
  },
  {
    id: 278,
    title: "The Shawshank Redemption",
    originalTitle: "The Shawshank Redemption",
    releaseDate: "1994-09-23",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/kXfqFcTe2tmt0cqRu49x8WwJ3Uf.jpg",
    overview: "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.",
    genres: ["Drama", "Crime"],
    genreIds: [18, 80],
    popularity: 132.8,
    tmdbRating: 8.7,
    tmdbVotes: 27800,
    formattedTmdbVotes: "27.8K",
    imdbId: "tt0111161",
    imdbRating: 9.3,
    imdbVotes: 2900000,
    formattedImdbVotes: "2.9M",
    qualityScore: 9.32,
    runtime: 142,
    formattedRuntime: "2h 22m",
    director: "Frank Darabont",
    trailerKey: "PLl99DlL6b4",
    rottenTomatoes: "91%",
    metascore: "82",
    rated: "R"
  },
  {
    id: 238,
    title: "The Godfather",
    originalTitle: "The Godfather",
    releaseDate: "1972-03-14",
    year: 1972,
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWF9x8WwJ3UfM5Ny6.jpg",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son steps in.",
    genres: ["Drama", "Crime"],
    genreIds: [18, 80],
    popularity: 125.1,
    tmdbRating: 8.7,
    tmdbVotes: 20400,
    formattedTmdbVotes: "20.4K",
    imdbId: "tt0068646",
    imdbRating: 9.2,
    imdbVotes: 2050000,
    formattedImdbVotes: "2.0M",
    qualityScore: 9.21,
    runtime: 175,
    formattedRuntime: "2h 55m",
    director: "Francis Ford Coppola",
    trailerKey: "sY1S34973zA",
    rottenTomatoes: "97%",
    metascore: "100",
    rated: "R"
  },
  {
    id: 680,
    title: "Pulp Fiction",
    originalTitle: "Pulp Fiction",
    releaseDate: "1994-09-10",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
    genres: ["Thriller", "Crime"],
    genreIds: [53, 80],
    popularity: 110.6,
    tmdbRating: 8.5,
    tmdbVotes: 27500,
    formattedTmdbVotes: "27.5K",
    imdbId: "tt0110912",
    imdbRating: 8.9,
    imdbVotes: 2200000,
    formattedImdbVotes: "2.2M",
    qualityScore: 8.92,
    runtime: 154,
    formattedRuntime: "2h 34m",
    director: "Quentin Tarantino",
    trailerKey: "s7EdQ4FqbhY",
    rottenTomatoes: "92%",
    metascore: "95",
    rated: "R"
  },
  {
    id: 550,
    title: "Fight Club",
    originalTitle: "Fight Club",
    releaseDate: "1999-10-15",
    year: 1999,
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    overview: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.",
    genres: ["Drama"],
    genreIds: [18],
    popularity: 104.3,
    tmdbRating: 8.4,
    tmdbVotes: 29000,
    formattedTmdbVotes: "29.0K",
    imdbId: "tt0137523",
    imdbRating: 8.8,
    imdbVotes: 2300000,
    formattedImdbVotes: "2.3M",
    qualityScore: 8.82,
    runtime: 139,
    formattedRuntime: "2h 19m",
    director: "David Fincher",
    trailerKey: "qtRKdVHc-cE",
    rottenTomatoes: "79%",
    metascore: "67",
    rated: "R"
  },
  {
    id: 13,
    title: "Forrest Gump",
    originalTitle: "Forrest Gump",
    releaseDate: "1994-06-23",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/arw2VCBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7c9R2aJ7X6k7k7b1q8l9x7p6v4w.jpg",
    overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do.",
    genres: ["Comedy", "Drama", "Romance"],
    genreIds: [35, 18, 10749],
    popularity: 99.8,
    tmdbRating: 8.5,
    tmdbVotes: 27100,
    formattedTmdbVotes: "27.1K",
    imdbId: "tt0109830",
    imdbRating: 8.8,
    imdbVotes: 2250000,
    formattedImdbVotes: "2.2M",
    qualityScore: 8.81,
    runtime: 142,
    formattedRuntime: "2h 22m",
    director: "Robert Zemeckis",
    trailerKey: "bLvqoHBptjg",
    rottenTomatoes: "71%",
    metascore: "82",
    rated: "PG-13"
  },
  {
    id: 872585,
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    releaseDate: "2023-07-19",
    year: 2023,
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0s9x8WwJ3UfM.jpg",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    genres: ["Drama", "History"],
    genreIds: [18, 36],
    popularity: 165.7,
    tmdbRating: 8.1,
    tmdbVotes: 9800,
    formattedTmdbVotes: "9.8K",
    imdbId: "tt15398776",
    imdbRating: 8.9,
    imdbVotes: 850000,
    formattedImdbVotes: "850K",
    qualityScore: 8.92,
    runtime: 180,
    formattedRuntime: "3h 0m",
    director: "Christopher Nolan",
    trailerKey: "uYPbbksJxIg",
    rottenTomatoes: "93%",
    metascore: "89",
    rated: "R"
  },
  {
    id: 120,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    originalTitle: "The Fellowship of the Ring",
    releaseDate: "2001-12-18",
    year: 2001,
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9DeGfFIqjphAvLf6yaBPAnBtYMe.jpg",
    overview: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home behind in order to begin an epic quest to destroy the One Ring.",
    genres: ["Adventure", "Fantasy", "Action"],
    genreIds: [12, 14, 28],
    popularity: 115.3,
    tmdbRating: 8.4,
    tmdbVotes: 24700,
    formattedTmdbVotes: "24.7K",
    imdbId: "tt0120737",
    imdbRating: 8.9,
    imdbVotes: 2020000,
    formattedImdbVotes: "2.0M",
    qualityScore: 8.91,
    runtime: 178,
    formattedRuntime: "2h 58m",
    director: "Peter Jackson",
    trailerKey: "V75dMMIW2B4",
    rottenTomatoes: "92%",
    metascore: "92",
    rated: "PG-13"
  },
  {
    id: 122,
    title: "The Lord of the Rings: The Return of the King",
    originalTitle: "The Return of the King",
    releaseDate: "2003-12-01",
    year: 2003,
    poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lXhgCODAbBXL5buk59x8WwJ3UfM.jpg",
    overview: "As armies mass for a final battle that will decide the fate of the world -- and powerful, ancient forces of Light and Dark compete to determine the outcome -- one member of the Fellowship of the Ring is revealed as the noble heir to the throne.",
    genres: ["Adventure", "Fantasy", "Action"],
    genreIds: [12, 14, 28],
    popularity: 118.9,
    tmdbRating: 8.5,
    tmdbVotes: 23600,
    formattedTmdbVotes: "23.6K",
    imdbId: "tt0167260",
    imdbRating: 9.0,
    imdbVotes: 2000000,
    formattedImdbVotes: "2.0M",
    qualityScore: 9.02,
    runtime: 201,
    formattedRuntime: "3h 21m",
    director: "Peter Jackson",
    trailerKey: "r5X-hFf6Bwo",
    rottenTomatoes: "94%",
    metascore: "94",
    rated: "PG-13"
  },
  {
    id: 313369,
    title: "La La Land",
    originalTitle: "La La Land",
    releaseDate: "2016-11-29",
    year: 2016,
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkVJt0Rf0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nadTlnTE6DdgmYsN4C5aK8l9x7p.jpg",
    overview: "Mia, an aspiring actress, and Sebastian, a dedicated jazz musician, are struggling to make ends meet in a city known for crushing hopes and breaking hearts.",
    genres: ["Comedy", "Drama", "Romance", "Music"],
    genreIds: [35, 18, 10749, 10402],
    popularity: 84.6,
    tmdbRating: 7.9,
    tmdbVotes: 16500,
    formattedTmdbVotes: "16.5K",
    imdbId: "tt3783958",
    imdbRating: 8.0,
    imdbVotes: 660000,
    formattedImdbVotes: "660K",
    qualityScore: 8.02,
    runtime: 128,
    formattedRuntime: "2h 8m",
    director: "Damien Chazelle",
    trailerKey: "0pdqf4P9MB8",
    rottenTomatoes: "91%",
    metascore: "94",
    rated: "PG-13"
  },
  {
    id: 38,
    title: "Eternal Sunshine of the Spotless Mind",
    originalTitle: "Eternal Sunshine of the Spotless Mind",
    releaseDate: "2004-03-19",
    year: 2004,
    poster: "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7k8l9x7p6v4w2y1z5mNy6hL4tY9.jpg",
    overview: "Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realizes that he still loves her.",
    genres: ["Science Fiction", "Drama", "Romance"],
    genreIds: [878, 18, 10749],
    popularity: 76.5,
    tmdbRating: 8.1,
    tmdbVotes: 14400,
    formattedTmdbVotes: "14.4K",
    imdbId: "tt0338013",
    imdbRating: 8.3,
    imdbVotes: 1100000,
    formattedImdbVotes: "1.1M",
    qualityScore: 8.31,
    runtime: 108,
    formattedRuntime: "1h 48m",
    director: "Michel Gondry",
    trailerKey: "yE-f1BMqCQI",
    rottenTomatoes: "92%",
    metascore: "89",
    rated: "R"
  },
  {
    id: 129,
    title: "Spirited Away",
    originalTitle: "千と千尋の神隠し",
    releaseDate: "2001-07-20",
    year: 2001,
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mSDmvRmCPgZStQvB58OQvJ65N0.jpg",
    overview: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    genres: ["Animation", "Family", "Fantasy"],
    genreIds: [16, 10751, 14],
    popularity: 112.4,
    tmdbRating: 8.5,
    tmdbVotes: 16100,
    formattedTmdbVotes: "16.1K",
    imdbId: "tt0245429",
    imdbRating: 8.6,
    imdbVotes: 870000,
    formattedImdbVotes: "870K",
    qualityScore: 8.61,
    runtime: 125,
    formattedRuntime: "2h 5m",
    director: "Hayao Miyazaki",
    trailerKey: "ByXuk9QqQkk",
    rottenTomatoes: "96%",
    metascore: "96",
    rated: "PG"
  },
  {
    id: 324857,
    title: "Spider-Man: Into the Spider-Verse",
    originalTitle: "Spider-Man: Into the Spider-Verse",
    releaseDate: "2018-12-06",
    year: 2018,
    poster: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7d6FTSfvxWgmPOcw29c8LdG76C9.jpg",
    overview: "Teen Miles Morales becomes the new Spider-Man, joining other Spider-Heroes from parallel dimensions to stop a menace to all reality.",
    genres: ["Animation", "Action", "Adventure", "Science Fiction"],
    genreIds: [16, 28, 12, 878],
    popularity: 128.5,
    tmdbRating: 8.4,
    tmdbVotes: 15100,
    formattedTmdbVotes: "15.1K",
    imdbId: "tt4633694",
    imdbRating: 8.4,
    imdbVotes: 690000,
    formattedImdbVotes: "690K",
    qualityScore: 8.42,
    runtime: 117,
    formattedRuntime: "1h 57m",
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    trailerKey: "tg52up16eq0",
    rottenTomatoes: "97%",
    metascore: "87",
    rated: "PG"
  },
  {
    id: 68718,
    title: "Django Unchained",
    originalTitle: "Django Unchained",
    releaseDate: "2012-12-25",
    year: 2012,
    poster: "https://image.tmdb.org/t/p/w500/7oWY8vdWW7thTzWh3OKYRkWUlD5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2AKG5f2X2V6b4l1z5mNy6hL4tY9.jpg",
    overview: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    genres: ["Drama", "Western"],
    genreIds: [18, 37],
    popularity: 105.7,
    tmdbRating: 8.2,
    tmdbVotes: 25600,
    formattedTmdbVotes: "25.6K",
    imdbId: "tt1853728",
    imdbRating: 8.5,
    imdbVotes: 1700000,
    formattedImdbVotes: "1.7M",
    qualityScore: 8.51,
    runtime: 165,
    formattedRuntime: "2h 45m",
    director: "Quentin Tarantino",
    trailerKey: "0fUCuvNlOCg",
    rottenTomatoes: "87%",
    metascore: "81",
    rated: "R"
  },
  {
    id: 6977,
    title: "No Country for Old Men",
    originalTitle: "No Country for Old Men",
    releaseDate: "2007-11-09",
    year: 2007,
    poster: "https://image.tmdb.org/t/p/w500/6d5XOczFq75fP1qL0Uq8WwJ3UfM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8j1lQ1X7v4G5m1y2V6b4l1z5mNy.jpg",
    overview: "Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it.",
    genres: ["Crime", "Drama", "Thriller", "Western"],
    genreIds: [80, 18, 53, 37],
    popularity: 79.4,
    tmdbRating: 7.9,
    tmdbVotes: 11700,
    formattedTmdbVotes: "11.7K",
    imdbId: "tt0477348",
    imdbRating: 8.2,
    imdbVotes: 1100000,
    formattedImdbVotes: "1.1M",
    qualityScore: 8.21,
    runtime: 122,
    formattedRuntime: "2h 2m",
    director: "Joel Coen, Ethan Coen",
    trailerKey: "38A__WT3-o0",
    rottenTomatoes: "93%",
    metascore: "92",
    rated: "R"
  },
  {
    id: 244786,
    title: "Whiplash",
    originalTitle: "Whiplash",
    releaseDate: "2014-10-10",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6bbZ6XN2L0rPYkEWjzgFlBXCAVB.jpg",
    overview: "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost.",
    genres: ["Drama", "Music"],
    genreIds: [18, 10402],
    popularity: 92.1,
    tmdbRating: 8.4,
    tmdbVotes: 14700,
    formattedTmdbVotes: "14.7K",
    imdbId: "tt2582802",
    imdbRating: 8.5,
    imdbVotes: 1000000,
    formattedImdbVotes: "1.0M",
    qualityScore: 8.51,
    runtime: 106,
    formattedRuntime: "1h 46m",
    director: "Damien Chazelle",
    trailerKey: "7d_jQycdQGo",
    rottenTomatoes: "94%",
    metascore: "88",
    rated: "R"
  },
  {
    id: 8587,
    title: "The Lion King",
    originalTitle: "The Lion King",
    releaseDate: "1994-06-23",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/sKCr78jnAMMIvBhwvthvG23Xso0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/wVoXnLq8l9x7p6v4w2y1z5mNy6h.jpg",
    overview: "A young lion prince is cast out of his pride by his cruel uncle, who claims he was responsible for his father's death.",
    genres: ["Animation", "Family", "Drama"],
    genreIds: [16, 10751, 18],
    popularity: 110.3,
    tmdbRating: 8.3,
    tmdbVotes: 18100,
    formattedTmdbVotes: "18.1K",
    imdbId: "tt0110357",
    imdbRating: 8.5,
    imdbVotes: 1150000,
    formattedImdbVotes: "1.1M",
    qualityScore: 8.51,
    runtime: 89,
    formattedRuntime: "1h 29m",
    director: "Roger Allers, Rob Minkoff",
    trailerKey: "4sj1MT05MQ4",
    rottenTomatoes: "93%",
    metascore: "88",
    rated: "G"
  },
  {
    id: 354912,
    title: "Coco",
    originalTitle: "Coco",
    releaseDate: "2017-10-27",
    year: 2017,
    poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/askg3SMvhqEl4OL52YuvdtQw40C.jpg",
    overview: "Despite his family's baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz.",
    genres: ["Animation", "Family", "Comedy", "Music", "Adventure"],
    genreIds: [16, 10751, 35, 10402, 12],
    popularity: 102.8,
    tmdbRating: 8.2,
    tmdbVotes: 18900,
    formattedTmdbVotes: "18.9K",
    imdbId: "tt2380307",
    imdbRating: 8.4,
    imdbVotes: 580000,
    formattedImdbVotes: "580K",
    qualityScore: 8.41,
    runtime: 105,
    formattedRuntime: "1h 45m",
    director: "Lee Unkrich",
    trailerKey: "xlnPHQ3TLX8",
    rottenTomatoes: "97%",
    metascore: "81",
    rated: "PG"
  },
  {
    id: 19404,
    title: "Dilwale Dulhania Le Jayenge",
    originalTitle: "दिलवाले दुल्हनिया ले जायेंगे",
    releaseDate: "1995-10-20",
    year: 1995,
    poster: "https://image.tmdb.org/t/p/w500/lf9RTEoMan2ghR1vWNe2lcSd19u.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/90DAhS5f2X2V6b4l1z5mNy6hL4t.jpg",
    overview: "Raj and Simran meet on a train trip through Europe and fall in love, but must overcome her conservative father's objections back in India.",
    genres: ["Comedy", "Drama", "Romance"],
    genreIds: [35, 18, 10749],
    popularity: 75.3,
    tmdbRating: 8.5,
    tmdbVotes: 4400,
    formattedTmdbVotes: "4.4K",
    imdbId: "tt0112870",
    imdbRating: 8.0,
    imdbVotes: 76000,
    formattedImdbVotes: "76K",
    qualityScore: 7.98,
    runtime: 189,
    formattedRuntime: "3h 9m",
    director: "Aditya Chopra",
    trailerKey: "c25GKl5VNeY",
    rottenTomatoes: "100%",
    metascore: "80",
    rated: "Not Rated"
  },
  {
    id: 597,
    title: "Titanic",
    originalTitle: "Titanic",
    releaseDate: "1997-11-18",
    year: 1997,
    poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kFUtYCeSTT0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yDI6D5ZQh67YU4r2ms8qcSbAviZ.jpg",
    overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiance.",
    genres: ["Drama", "Romance"],
    genreIds: [18, 10749],
    popularity: 135.6,
    tmdbRating: 7.9,
    tmdbVotes: 24700,
    formattedTmdbVotes: "24.7K",
    imdbId: "tt0120338",
    imdbRating: 7.9,
    imdbVotes: 1300000,
    formattedImdbVotes: "1.3M",
    qualityScore: 7.92,
    runtime: 194,
    formattedRuntime: "3h 14m",
    director: "James Cameron",
    trailerKey: "kVrqfY8mTFI",
    rottenTomatoes: "88%",
    metascore: "75",
    rated: "PG-13"
  },
  {
    id: 8392,
    title: "The Grand Budapest Hotel",
    originalTitle: "The Grand Budapest Hotel",
    releaseDate: "2014-02-26",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWX97t6Q0L5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/wVoXnLq8l9x7p6v4w2y1z5mNy6h.jpg",
    overview: "The Grand Budapest Hotel tells of a legendary concierge at a famous European hotel between the wars and his friendship with a young employee who becomes his trusted protégé.",
    genres: ["Comedy", "Drama", "Adventure"],
    genreIds: [35, 18, 12],
    popularity: 76.9,
    tmdbRating: 8.0,
    tmdbVotes: 14200,
    formattedTmdbVotes: "14.2K",
    imdbId: "tt2278388",
    imdbRating: 8.1,
    imdbVotes: 870000,
    formattedImdbVotes: "870K",
    qualityScore: 8.11,
    runtime: 99,
    formattedRuntime: "1h 39m",
    director: "Wes Anderson",
    trailerKey: "1Fg5iWmQjwk",
    rottenTomatoes: "92%",
    metascore: "88",
    rated: "R"
  },
  {
    id: 115,
    title: "The Big Lebowski",
    originalTitle: "The Big Lebowski",
    releaseDate: "1998-03-06",
    year: 1998,
    poster: "https://image.tmdb.org/t/p/w500/aKzkrhZ8hW2qL6xV7m6L4h1z5vN.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8j1lQ1X7v4G5m1y2V6b4l1z5mNy.jpg",
    overview: "Jeffrey 'The Dude' Lebowski, a Los Angeles slacker who only wants to bowl and drink white Russians, is mistaken for another Jeffrey Lebowski, a wheelchair-bound millionaire.",
    genres: ["Comedy", "Crime"],
    genreIds: [35, 80],
    popularity: 68.3,
    tmdbRating: 7.8,
    tmdbVotes: 10800,
    formattedTmdbVotes: "10.8K",
    imdbId: "tt0118715",
    imdbRating: 8.1,
    imdbVotes: 850000,
    formattedImdbVotes: "850K",
    qualityScore: 8.11,
    runtime: 117,
    formattedRuntime: "1h 57m",
    director: "Joel Coen, Ethan Coen",
    trailerKey: "cd-go0oBF4Y",
    rottenTomatoes: "83%",
    metascore: "71",
    rated: "R"
  },
  {
    id: 37165,
    title: "The Truman Show",
    originalTitle: "The Truman Show",
    releaseDate: "1998-06-04",
    year: 1998,
    poster: "https://image.tmdb.org/t/p/w500/vuza0WqY239gB2AKG5f2X2V6b4l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/v2A5b1q8l9x7p6v4w2y1z5mNy6h.jpg",
    overview: "Truman Burbank is the star of The Truman Show, a 24-hour-a-day reality TV program that is broadcast live around the globe from the day he was born.",
    genres: ["Comedy", "Drama"],
    genreIds: [35, 18],
    popularity: 82.5,
    tmdbRating: 8.1,
    tmdbVotes: 17500,
    formattedTmdbVotes: "17.5K",
    imdbId: "tt0120382",
    imdbRating: 8.2,
    imdbVotes: 1200000,
    formattedImdbVotes: "1.2M",
    qualityScore: 8.21,
    runtime: 103,
    formattedRuntime: "1h 43m",
    director: "Peter Weir",
    trailerKey: "dlnmQbPGuls",
    rottenTomatoes: "95%",
    metascore: "90",
    rated: "PG"
  },
  {
    id: 857,
    title: "Saving Private Ryan",
    originalTitle: "Saving Private Ryan",
    releaseDate: "1998-07-24",
    year: 1998,
    poster: "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8xSRpnf7Cv8v1nNy.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/jT5A0g1q8l9x7p6v4w2y1z5mNy6.jpg",
    overview: "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
    genres: ["Drama", "History", "War"],
    genreIds: [18, 36, 10752],
    popularity: 97.4,
    tmdbRating: 8.2,
    tmdbVotes: 15400,
    formattedTmdbVotes: "15.4K",
    imdbId: "tt0120815",
    imdbRating: 8.6,
    imdbVotes: 1500000,
    formattedImdbVotes: "1.5M",
    qualityScore: 8.61,
    runtime: 169,
    formattedRuntime: "2h 49m",
    director: "Steven Spielberg",
    trailerKey: "zwhP5b4tD6g",
    rottenTomatoes: "94%",
    metascore: "91",
    rated: "R"
  },
  {
    id: 530915,
    title: "1917",
    originalTitle: "1917",
    releaseDate: "2019-12-25",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1nx4Pv8nlAYLsyAc.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2WZyGACbSLoepR8kL4tY9X7m6L4.jpg",
    overview: "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
    genres: ["War", "Action", "Drama", "History"],
    genreIds: [10752, 28, 18, 36],
    popularity: 88.2,
    tmdbRating: 8.0,
    tmdbVotes: 12500,
    formattedTmdbVotes: "12.5K",
    imdbId: "tt8579674",
    imdbRating: 8.2,
    imdbVotes: 660000,
    formattedImdbVotes: "660K",
    qualityScore: 8.22,
    runtime: 119,
    formattedRuntime: "1h 59m",
    director: "Sam Mendes",
    trailerKey: "YqNYrYUiMfg",
    rottenTomatoes: "89%",
    metascore: "78",
    rated: "R"
  },
  {
    id: 16869,
    title: "Inglourious Basterds",
    originalTitle: "Inglourious Basterds",
    releaseDate: "2009-08-19",
    year: 2009,
    poster: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDD5Ju077vfqaKRv0f.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    overview: "In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as 'The Basterds' are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis.",
    genres: ["Drama", "Thriller", "War"],
    genreIds: [18, 53, 10752],
    popularity: 96.5,
    tmdbRating: 8.2,
    tmdbVotes: 21900,
    formattedTmdbVotes: "21.9K",
    imdbId: "tt0361748",
    imdbRating: 8.4,
    imdbVotes: 1600000,
    formattedImdbVotes: "1.6M",
    qualityScore: 8.42,
    runtime: 153,
    formattedRuntime: "2h 33m",
    director: "Quentin Tarantino",
    trailerKey: "KnrRy6kSFF0",
    rottenTomatoes: "89%",
    metascore: "69",
    rated: "R"
  }
];

export const DEMO_REVIEWS = [
  {
    id: "rev1",
    author: "CinemaVerite",
    avatar: null,
    rating: 10,
    content: "An absolute masterclass in cinematic suspense. The direction, atmospheric sound design, and psychological escalation are relentless from start to finish.",
    createdAt: "2024-03-15T14:22:00Z"
  },
  {
    id: "rev2",
    author: "FilmBuff99",
    avatar: null,
    rating: 9,
    content: "One of the most genuinely unsettling and thoughtfully crafted films of the decade. The performances are remarkable, especially in conveying unspoken grief and tension.",
    createdAt: "2024-01-10T19:40:00Z"
  },
  {
    id: "rev3",
    author: "ScreenScribe",
    avatar: null,
    rating: 8,
    content: "Visually stunning with profound thematic ambition. Even on repeat viewings, the nuances of the narrative reward patient and attentive viewing.",
    createdAt: "2023-11-20T08:15:00Z"
  }
];
